### ISSUE TITLE
loads() is broken

### ISSUE THREAD

**Issue by dargueta-work** [djc/rnc2rng#10]
When using `rnc2rng` in `lxml.etree.RelaxNG.from_rnc_string()` as described [here](http://lxml.de/validation.html#relaxng), we get a crash with the following stack trace:

```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/dargueta/git/clinicalfiles/setup.py", line 107, in <module>
        compile_all()
      File "/Users/dargueta/git/clinicalfiles/setup.py", line 78, in compile_all
        fileformat_xsd = xml.RelaxNG.from_rnc_string(rnc_fd.read())
      File "src/lxml/relaxng.pxi", line 150, in lxml.etree.RelaxNG.from_rnc_string (src/lxml/lxml.etree.c:195588)
      File "/Users/dargueta/.pyenv/versions/3.5.2/envs/clinical_files_35/lib/python3.5/site-packages/rnc2rng/__init__.py", line 7, in loads
        return parser.parse(src)
      File "/Users/dargueta/.pyenv/versions/3.5.2/envs/clinical_files_35/lib/python3.5/site-packages/rnc2rng/parser.py", line 529, in parse
        return parser.parse(lex(src), state=State(fn, src))
    UnboundLocalError: local variable 'fn' referenced before assignment
```

The problem is in `parser.parse()`, specifically [here](https://github.com/djc/rnc2rng/blob/master/rnc2rng/parser.py#L543-L548). If `parse()` is only given source code and no file, there is no `else` clause to set `fn`. We can fix this like so:

```py
    elif f is not None:
        fn, src = f.name, f.read()
    else:
        fn = None
```

`State` properly handles a null filename (see [here](https://github.com/djc/rnc2rng/blob/master/rnc2rng/parser.py#L532)) so we know that `None` is a good default value.

**Comment by ksharenkov** [comment]
Have you any plans to make release with this fix?
with PyPI https://pypi.python.org/pypi/rnc2rng 
:)

**Comment by djc** [comment]
Find version 2.5 on a PyPI mirror near you now! 😄

**Comment by ksharenkov** [comment]
Wow. Thanks. Its crazy fast :)
